# Generated by Django 5.1.6 on 2025-02-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfunds",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
